import 'package:flutter/material.dart' show Brightness, Color, ColorScheme, Colors, ThemeData, VisualDensity;

ThemeData get darkTheme => ThemeData(
      visualDensity: VisualDensity.compact,
      colorSchemeSeed: Colors.teal,
      // colorScheme: tealDarkColorScheme,
      brightness: Brightness.dark,
      useMaterial3: true,
    );

const tealDarkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF009688),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF4DB6AC),
  onPrimaryContainer: Color(0xFF003E2F),
  secondary: Color(0xFFF57C00),
  onSecondary: Color(0xFF000000),
  secondaryContainer: Color(0xFFFFD8B3),
  onSecondaryContainer: Color(0xFF000000),
  tertiary: Color(0xFF4CAF50),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFD8E9CD),
  onTertiaryContainer: Color(0xFF003523),
  error: Color(0xFFF44336),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFBAB0),
  onErrorContainer: Color(0xFF000000),
  background: Color(0xFF121212),
  onBackground: Color(0xFFFFFFFF),
  surface: Color(0xFF212121),
  onSurface: Color(0xFFFFFFFF),
  surfaceVariant: Color(0xFF373737),
  onSurfaceVariant: Color(0xFFFFFFFF),
  outline: Color(0xFFAFAFAF),
  outlineVariant: Color(0xFF575757),
  shadow: Color(0x26000000),
  scrim: Color(0x4C000000),
  inverseSurface: Color(0xFFF5F5F5),
  onInverseSurface: Color(0xFF000000),
  inversePrimary: Color(0xFF262626),
  surfaceTint: Color(0xFF009688),
);
